-- GroupWise AI schema (generated by backend/scripts/export_schema.py)
-- Money is stored as BIGINT paisa (1 taka = 100 paisa).

CREATE TABLE audit_log (
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	user_id VARCHAR(36), 
	group_id VARCHAR(36), 
	action VARCHAR(40) NOT NULL, 
	outcome VARCHAR(16) NOT NULL, 
	ip_hash VARCHAR(16), 
	subject_hash VARCHAR(16), 
	detail JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_audit_action_time ON audit_log (action, created_at);
CREATE INDEX ix_audit_log_user_id ON audit_log (user_id);
CREATE INDEX ix_audit_log_subject_hash ON audit_log (subject_hash);
CREATE INDEX ix_audit_log_created_at ON audit_log (created_at);

CREATE TABLE outbox_events (
	id VARCHAR(36) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	topic VARCHAR(40) NOT NULL, 
	group_id VARCHAR(36), 
	aggregate_id VARCHAR(36), 
	payload JSON NOT NULL, 
	published_at TIMESTAMP WITHOUT TIME ZONE, 
	attempts INTEGER NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_outbox_unpublished ON outbox_events (published_at, created_at);
CREATE INDEX ix_outbox_events_group_id ON outbox_events (group_id);

CREATE TABLE rate_limit_events (
	id VARCHAR(36) NOT NULL, 
	key VARCHAR(80) NOT NULL, 
	at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_rate_key_time ON rate_limit_events (key, at);

CREATE TABLE revoked_tokens (
	jti VARCHAR(36) NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (jti)
);

CREATE INDEX ix_revoked_tokens_expires_at ON revoked_tokens (expires_at);

CREATE TABLE users (
	id VARCHAR(36) NOT NULL, 
	email VARCHAR(255), 
	display_name VARCHAR(80) NOT NULL, 
	password_hash VARCHAR(255), 
	auth_provider VARCHAR(16) NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	avatar_color VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE TABLE groups (
	id VARCHAR(36) NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	description VARCHAR(280), 
	group_type VARCHAR(16) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	invite_code VARCHAR(16) NOT NULL, 
	monthly_budget_paisa BIGINT, 
	created_by VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	data_version INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (invite_code), 
	FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL
);


CREATE TABLE session_epochs (
	user_id VARCHAR(36) NOT NULL, 
	not_before TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE activity_days (
	id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	day DATE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_activity_day UNIQUE (user_id, group_id, day), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE INDEX ix_activity_days_group_id ON activity_days (group_id);
CREATE INDEX ix_activity_days_user_id ON activity_days (user_id);

CREATE TABLE ai_outputs (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	kind VARCHAR(32) NOT NULL, 
	entity_id VARCHAR(36), 
	model_name VARCHAR(80) NOT NULL, 
	model_version VARCHAR(40) NOT NULL, 
	confidence FLOAT, 
	payload JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE INDEX ix_ai_outputs_group_id ON ai_outputs (group_id);

CREATE TABLE experiment_assignments (
	group_id VARCHAR(36) NOT NULL, 
	experiment VARCHAR(40) NOT NULL, 
	arm VARCHAR(16) NOT NULL, 
	assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (group_id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);


CREATE TABLE goals (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	title VARCHAR(80) NOT NULL, 
	description VARCHAR(280), 
	target_paisa BIGINT NOT NULL, 
	start_date DATE NOT NULL, 
	deadline DATE NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	created_by_user_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_goals_group_id ON goals (group_id);

CREATE TABLE group_members (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36), 
	display_name VARCHAR(80) NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	avatar_color VARCHAR(16) NOT NULL, 
	joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	left_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_member_user UNIQUE (group_id, user_id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_group_members_user_id ON group_members (user_id);
CREATE INDEX ix_group_members_group_id ON group_members (group_id);

CREATE TABLE group_settings (
	group_id VARCHAR(36) NOT NULL, 
	dynamics_enabled BOOLEAN NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_by_user_id VARCHAR(36), 
	PRIMARY KEY (group_id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);


CREATE TABLE notifications (
	id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	kind VARCHAR(24) NOT NULL, 
	title VARCHAR(120) NOT NULL, 
	body VARCHAR(400) NOT NULL, 
	link VARCHAR(200), 
	is_read BOOLEAN NOT NULL, 
	dedupe_key VARCHAR(120), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_notification_dedupe UNIQUE (user_id, dedupe_key), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE INDEX ix_notifications_user_id ON notifications (user_id);

CREATE TABLE recommendation_actions (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36), 
	recommendation_key VARCHAR(80) NOT NULL, 
	action VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_recommendation_actions_group_id ON recommendation_actions (group_id);

CREATE TABLE expenses (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	payer_member_id VARCHAR(36) NOT NULL, 
	created_by_user_id VARCHAR(36), 
	amount_paisa BIGINT NOT NULL, 
	description VARCHAR(200) NOT NULL, 
	merchant VARCHAR(120), 
	category VARCHAR(40) NOT NULL, 
	subcategory VARCHAR(60) NOT NULL, 
	expense_type VARCHAR(60) NOT NULL, 
	category_source VARCHAR(16) NOT NULL, 
	category_confidence FLOAT, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	payment_method VARCHAR(24) NOT NULL, 
	split_method VARCHAR(16) NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	anomaly_score FLOAT, 
	anomaly_status VARCHAR(16) NOT NULL, 
	anomaly_reasons JSON, 
	is_deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(payer_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_expenses_group_id ON expenses (group_id);
CREATE INDEX ix_expenses_occurred_at ON expenses (occurred_at);
CREATE INDEX ix_expense_group_time ON expenses (group_id, occurred_at);

CREATE TABLE goal_contributions (
	id VARCHAR(36) NOT NULL, 
	goal_id VARCHAR(36) NOT NULL, 
	member_id VARCHAR(36) NOT NULL, 
	amount_paisa BIGINT NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	note VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(goal_id) REFERENCES goals (id) ON DELETE CASCADE, 
	FOREIGN KEY(member_id) REFERENCES group_members (id) ON DELETE CASCADE
);

CREATE INDEX ix_goal_contributions_goal_id ON goal_contributions (goal_id);

CREATE TABLE payment_requests (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	purpose VARCHAR(24) NOT NULL, 
	payer_member_id VARCHAR(36) NOT NULL, 
	payee_member_id VARCHAR(36), 
	goal_id VARCHAR(36), 
	amount_paisa BIGINT NOT NULL, 
	reference VARCHAR(24) NOT NULL, 
	provider VARCHAR(24) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	provider_txn_id VARCHAR(64), 
	result_id VARCHAR(36), 
	created_by_user_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(payer_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(payee_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(goal_id) REFERENCES goals (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX ix_payment_requests_reference ON payment_requests (reference);
CREATE INDEX ix_payment_requests_group_id ON payment_requests (group_id);

CREATE TABLE settlements (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	from_member_id VARCHAR(36) NOT NULL, 
	to_member_id VARCHAR(36) NOT NULL, 
	amount_paisa BIGINT NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	note VARCHAR(200), 
	created_by_user_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(from_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(to_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_settlements_group_id ON settlements (group_id);

CREATE TABLE wallet_import_items (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	member_id VARCHAR(36) NOT NULL, 
	provider_txn_id VARCHAR(64) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	entity_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_wallet_import_txn UNIQUE (group_id, member_id, provider_txn_id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(member_id) REFERENCES group_members (id) ON DELETE CASCADE
);

CREATE INDEX ix_wallet_import_items_group_id ON wallet_import_items (group_id);

CREATE TABLE category_feedback (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	expense_id VARCHAR(36), 
	user_id VARCHAR(36), 
	text VARCHAR(240) NOT NULL, 
	predicted_subcategory VARCHAR(60), 
	corrected_subcategory VARCHAR(60) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(expense_id) REFERENCES expenses (id) ON DELETE SET NULL, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_category_feedback_group_id ON category_feedback (group_id);

CREATE TABLE expense_splits (
	id VARCHAR(36) NOT NULL, 
	expense_id VARCHAR(36) NOT NULL, 
	member_id VARCHAR(36) NOT NULL, 
	share_paisa BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(expense_id) REFERENCES expenses (id) ON DELETE CASCADE, 
	FOREIGN KEY(member_id) REFERENCES group_members (id) ON DELETE CASCADE
);

CREATE INDEX ix_expense_splits_expense_id ON expense_splits (expense_id);
CREATE INDEX ix_expense_splits_member_id ON expense_splits (member_id);

-- Row-level security. The API (table owner) is the only write path. Through Supabase's Data API:
-- anon reads nothing; a signed-in user reads only rows of groups they are an active member of
-- (plus their own profile and notifications); security and operational tables are API-only.
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "outbox_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rate_limit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "revoked_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session_epochs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activity_days" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_outputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiment_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "group_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "group_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recommendation_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goal_contributions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settlements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "wallet_import_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "category_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expense_splits" ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION "public".gw_is_member(gid text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = "public", pg_temp AS $$
  SELECT EXISTS (SELECT 1 FROM group_members m WHERE m.group_id = gid
                 AND m.user_id = (SELECT auth.uid())::text AND m.status = 'active')
$$;
REVOKE ALL ON FUNCTION "public".gw_is_member(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION "public".gw_is_member(text) TO authenticated;
REVOKE ALL ON "audit_log" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "audit_log";
REVOKE ALL ON "audit_log" FROM authenticated;
REVOKE ALL ON "outbox_events" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "outbox_events";
REVOKE ALL ON "outbox_events" FROM authenticated;
REVOKE ALL ON "rate_limit_events" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "rate_limit_events";
REVOKE ALL ON "rate_limit_events" FROM authenticated;
REVOKE ALL ON "revoked_tokens" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "revoked_tokens";
REVOKE ALL ON "revoked_tokens" FROM authenticated;
REVOKE ALL ON "users" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "users";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "users" FROM authenticated;
CREATE POLICY gw_member_read ON "users" FOR SELECT TO authenticated USING (id = (select auth.uid())::text);
REVOKE ALL ON "groups" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "groups";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "groups" FROM authenticated;
CREATE POLICY gw_member_read ON "groups" FOR SELECT TO authenticated USING (gw_is_member(id));
REVOKE ALL ON "session_epochs" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "session_epochs";
REVOKE ALL ON "session_epochs" FROM authenticated;
REVOKE ALL ON "activity_days" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "activity_days";
REVOKE ALL ON "activity_days" FROM authenticated;
REVOKE ALL ON "ai_outputs" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "ai_outputs";
REVOKE ALL ON "ai_outputs" FROM authenticated;
REVOKE ALL ON "experiment_assignments" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "experiment_assignments";
REVOKE ALL ON "experiment_assignments" FROM authenticated;
REVOKE ALL ON "goals" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "goals";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "goals" FROM authenticated;
CREATE POLICY gw_member_read ON "goals" FOR SELECT TO authenticated USING (gw_is_member(group_id));
REVOKE ALL ON "group_members" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "group_members";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "group_members" FROM authenticated;
CREATE POLICY gw_member_read ON "group_members" FOR SELECT TO authenticated USING (gw_is_member(group_id));
REVOKE ALL ON "group_settings" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "group_settings";
REVOKE ALL ON "group_settings" FROM authenticated;
REVOKE ALL ON "notifications" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "notifications";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "notifications" FROM authenticated;
CREATE POLICY gw_member_read ON "notifications" FOR SELECT TO authenticated USING (user_id = (select auth.uid())::text);
REVOKE ALL ON "recommendation_actions" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "recommendation_actions";
REVOKE ALL ON "recommendation_actions" FROM authenticated;
REVOKE ALL ON "expenses" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "expenses";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "expenses" FROM authenticated;
CREATE POLICY gw_member_read ON "expenses" FOR SELECT TO authenticated USING (gw_is_member(group_id));
REVOKE ALL ON "goal_contributions" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "goal_contributions";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "goal_contributions" FROM authenticated;
CREATE POLICY gw_member_read ON "goal_contributions" FOR SELECT TO authenticated USING (exists (select 1 from goals g where g.id = goal_id and gw_is_member(g.group_id)));
REVOKE ALL ON "payment_requests" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "payment_requests";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "payment_requests" FROM authenticated;
CREATE POLICY gw_member_read ON "payment_requests" FOR SELECT TO authenticated USING (gw_is_member(group_id));
REVOKE ALL ON "settlements" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "settlements";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "settlements" FROM authenticated;
CREATE POLICY gw_member_read ON "settlements" FOR SELECT TO authenticated USING (gw_is_member(group_id));
REVOKE ALL ON "wallet_import_items" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "wallet_import_items";
REVOKE ALL ON "wallet_import_items" FROM authenticated;
REVOKE ALL ON "category_feedback" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "category_feedback";
REVOKE ALL ON "category_feedback" FROM authenticated;
REVOKE ALL ON "expense_splits" FROM anon;
DROP POLICY IF EXISTS gw_member_read ON "expense_splits";
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON "expense_splits" FROM authenticated;
CREATE POLICY gw_member_read ON "expense_splits" FOR SELECT TO authenticated USING (exists (select 1 from expenses e where e.id = expense_id and gw_is_member(e.group_id)));
