-- GroupWise AI schema (generated by backend/scripts/export_schema.py)
-- Money is stored as BIGINT paisa (1 taka = 100 paisa).

CREATE TABLE users (
	id VARCHAR(36) NOT NULL, 
	email VARCHAR(255), 
	display_name VARCHAR(80) NOT NULL, 
	password_hash VARCHAR(255), 
	auth_provider VARCHAR(16) NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	avatar_color VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE TABLE groups (
	id VARCHAR(36) NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	description VARCHAR(280), 
	group_type VARCHAR(16) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	invite_code VARCHAR(16) NOT NULL, 
	monthly_budget_paisa BIGINT, 
	created_by VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	data_version INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (invite_code), 
	FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL
);


CREATE TABLE ai_outputs (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	kind VARCHAR(32) NOT NULL, 
	entity_id VARCHAR(36), 
	model_name VARCHAR(80) NOT NULL, 
	model_version VARCHAR(40) NOT NULL, 
	confidence FLOAT, 
	payload JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE INDEX ix_ai_outputs_group_id ON ai_outputs (group_id);

CREATE TABLE goals (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	title VARCHAR(80) NOT NULL, 
	description VARCHAR(280), 
	target_paisa BIGINT NOT NULL, 
	start_date DATE NOT NULL, 
	deadline DATE NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	created_by_user_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_goals_group_id ON goals (group_id);

CREATE TABLE group_members (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36), 
	display_name VARCHAR(80) NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	avatar_color VARCHAR(16) NOT NULL, 
	joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	left_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_member_user UNIQUE (group_id, user_id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_group_members_user_id ON group_members (user_id);
CREATE INDEX ix_group_members_group_id ON group_members (group_id);

CREATE TABLE notifications (
	id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	kind VARCHAR(24) NOT NULL, 
	title VARCHAR(120) NOT NULL, 
	body VARCHAR(400) NOT NULL, 
	link VARCHAR(200), 
	is_read BOOLEAN NOT NULL, 
	dedupe_key VARCHAR(120), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_notification_dedupe UNIQUE (user_id, dedupe_key), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE INDEX ix_notifications_user_id ON notifications (user_id);

CREATE TABLE recommendation_actions (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	user_id VARCHAR(36), 
	recommendation_key VARCHAR(80) NOT NULL, 
	action VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_recommendation_actions_group_id ON recommendation_actions (group_id);

CREATE TABLE expenses (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	payer_member_id VARCHAR(36) NOT NULL, 
	created_by_user_id VARCHAR(36), 
	amount_paisa BIGINT NOT NULL, 
	description VARCHAR(200) NOT NULL, 
	merchant VARCHAR(120), 
	category VARCHAR(40) NOT NULL, 
	subcategory VARCHAR(60) NOT NULL, 
	expense_type VARCHAR(60) NOT NULL, 
	category_source VARCHAR(16) NOT NULL, 
	category_confidence FLOAT, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	payment_method VARCHAR(24) NOT NULL, 
	split_method VARCHAR(16) NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	anomaly_score FLOAT, 
	anomaly_status VARCHAR(16) NOT NULL, 
	anomaly_reasons JSON, 
	is_deleted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(payer_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_expense_group_time ON expenses (group_id, occurred_at);
CREATE INDEX ix_expenses_group_id ON expenses (group_id);
CREATE INDEX ix_expenses_occurred_at ON expenses (occurred_at);

CREATE TABLE goal_contributions (
	id VARCHAR(36) NOT NULL, 
	goal_id VARCHAR(36) NOT NULL, 
	member_id VARCHAR(36) NOT NULL, 
	amount_paisa BIGINT NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	note VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(goal_id) REFERENCES goals (id) ON DELETE CASCADE, 
	FOREIGN KEY(member_id) REFERENCES group_members (id) ON DELETE CASCADE
);

CREATE INDEX ix_goal_contributions_goal_id ON goal_contributions (goal_id);

CREATE TABLE settlements (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36) NOT NULL, 
	from_member_id VARCHAR(36) NOT NULL, 
	to_member_id VARCHAR(36) NOT NULL, 
	amount_paisa BIGINT NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	note VARCHAR(200), 
	created_by_user_id VARCHAR(36), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(from_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(to_member_id) REFERENCES group_members (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_settlements_group_id ON settlements (group_id);

CREATE TABLE category_feedback (
	id VARCHAR(36) NOT NULL, 
	group_id VARCHAR(36), 
	expense_id VARCHAR(36), 
	user_id VARCHAR(36), 
	text VARCHAR(240) NOT NULL, 
	predicted_subcategory VARCHAR(60), 
	corrected_subcategory VARCHAR(60) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES groups (id) ON DELETE CASCADE, 
	FOREIGN KEY(expense_id) REFERENCES expenses (id) ON DELETE SET NULL, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_category_feedback_group_id ON category_feedback (group_id);

CREATE TABLE expense_splits (
	id VARCHAR(36) NOT NULL, 
	expense_id VARCHAR(36) NOT NULL, 
	member_id VARCHAR(36) NOT NULL, 
	share_paisa BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(expense_id) REFERENCES expenses (id) ON DELETE CASCADE, 
	FOREIGN KEY(member_id) REFERENCES group_members (id) ON DELETE CASCADE
);

CREATE INDEX ix_expense_splits_expense_id ON expense_splits (expense_id);
CREATE INDEX ix_expense_splits_member_id ON expense_splits (member_id);

-- The API (server-side, postgres role) is the only data path. Enabling RLS with no policies
-- blocks the public anon/authenticated roles from reading these tables via the Data API.
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_outputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "group_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recommendation_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goal_contributions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settlements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "category_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expense_splits" ENABLE ROW LEVEL SECURITY;
