"""Export the PostgreSQL DDL (with row-level security) for Supabase.

Usage:  python -m scripts.export_schema > ../supabase/schema.sql

The API creates these tables automatically on startup; this file is for reviewing the schema or
creating it ahead of time in the Supabase SQL editor.
"""
from __future__ import annotations

import os

os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app import models  # noqa: E402,F401
from app.db import Base  # noqa: E402


def main() -> None:
    dialect = postgresql.dialect()
    print("-- GroupWise AI schema (generated by backend/scripts/export_schema.py)")
    print("-- Money is stored as BIGINT paisa (1 taka = 100 paisa).\n")
    for table in Base.metadata.sorted_tables:
        print(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in table.indexes:
            print(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        print()
    print("-- The API (server-side, postgres role) is the only data path. Enabling RLS with no policies")
    print("-- blocks the public anon/authenticated roles from reading these tables via the Data API.")
    for table in Base.metadata.sorted_tables:
        print(f'ALTER TABLE "{table.name}" ENABLE ROW LEVEL SECURITY;')


if __name__ == "__main__":
    main()
